sudo: required
services:
  - docker

before_install:
  - docker build -t sushilkadu/docker-client -f Dockerfile.dev .

script:
  - docker run -e CI=true sushilkadu/docker-client npm run test

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-073731903074"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
